# Sportsref - Euro

In [1]:
from sportsref import euro
import pandas as pd

Regenerating PSFConstants file
Regenerating GPFConstants file

In [2]:
p = euro.Player('luka-doncic-1')

## simple methods: Almost no changes

#### only change: Milos Teodosic Europe Stats -> Milos Teodosic

In [3]:
print(p.name())
print(p.age(2017))
print(p.height())

Luka Doncic
17.93972602739726
78

## Gamelogs - different url style

In [23]:
# new method: to me, would be useful/necessary
# because gamelogs are split by league and year

print(p.available_gamelogs())

[(2015, 'SPA'), (2016, 'ELG'), (2016, 'SPA'), (2017, 'ELG'), (2017, 'SPA'), (2018, 'ELG'), (2018, 'SPA')]

In [25]:
p.gamelog_basic(2015, 'SPA').head()

,boxscore_id,age,team_id,is_home,opp_id,game_result,mp,fg,fga,fg_pct,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,game_score
0,2015-04-30-real-madrid,16-061,Real-Madrid,True,Unicaja-Malaga,W,1.466667,1.0,1.0,1.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.7
1,2015-05-03-obradoiro,16-064,Real-Madrid,False,Obradoiro,W,1.750000,0.0,2.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.2
2,2015-05-20-vitoria,16-081,Real-Madrid,False,Vitoria,L,5.000000,0.0,0.0,NaN,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0
3,2015-05-29-real-madrid,16-090,Real-Madrid,True,Gran-Canaria,W,10.850000,1.0,3.0,0.333,...,0.0,3.0,3.0,0.0,0.0,0.0,1.0,0.0,2.0,0.2
4,2015-05-31-gran-canaria,16-092,Real-Madrid,False,Gran-Canaria,W,4.983333,0.0,0.0,NaN,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3

In [26]:
p.gamelog_basic(2018, 'ELG').head()

,boxscore_id,age,team_id,is_home,opp_id,game_result,mp,fg,fga,fg_pct,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,game_score
0,2017-10-12-anadolu-efes,18-226,Real-Madrid,False,Anadolu-Efes,W,26.600000,9.0,14.0,0.643,...,2.0,2.0,4.0,4.0,0.0,0.0,2.0,1.0,27.0,22.8
1,2017-10-19-real-madrid,18-233,Real-Madrid,True,Cska-Moscow,W,26.083333,2.0,8.0,0.250,...,1.0,5.0,6.0,2.0,2.0,1.0,2.0,2.0,14.0,11.9
2,2017-10-24-real-madrid,18-238,Real-Madrid,True,Milano,W,28.416667,7.0,14.0,0.500,...,2.0,6.0,8.0,5.0,3.0,0.0,1.0,0.0,27.0,28.3
3,2017-10-26-zalgiris,18-240,Real-Madrid,False,Zalgiris,W,27.750000,9.0,13.0,0.692,...,2.0,7.0,9.0,4.0,0.0,0.0,3.0,2.0,28.0,25.0
4,2017-11-02-real-madrid,18-247,Real-Madrid,True,Khimki,L,25.600000,3.0,10.0,0.300,...,2.0,5.0,7.0,3.0,1.0,0.0,3.0,1.0,12.0,8.8

## stat_tables:


### took out stats_per100, stats_advanced, stats_shooting, stats_pbp (data not on bballref)

### changed table_ids

### parameters:

### Kind (works the same)

### Level (needed, because different docs are pulled from)

#### -B (pulls from main milos-teodosic doc - default)
#### -C (pulls from milos-teodosic-club)
#### -E (pulls from milos-teodosic-tournament, which is Eurocup/Euroleague play)

## Test: level='B' - Both

In [4]:
df = p.stats_per_game(kind='R', level='B')

print(len(df))

4

In [5]:
df.head()

,season,lg_name,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,fg3a_per_g,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2015,Liga ACB,3.0,NaN,2.7,0.3,1.0,0.333,0.3,0.7,...,0.3,0.3,0.7,0.0,0.0,0.0,0.0,0.3,2.0,False
1,2016,"Liga ACB, EuroLeague",43.0,NaN,13.3,1.4,2.9,0.500,0.5,1.3,...,0.5,2.2,2.7,2.0,0.3,0.3,1.4,1.5,4.5,False
2,2017,"Liga ACB, EuroLeague",67.0,NaN,19.9,2.6,5.7,0.446,1.0,2.9,...,1.0,3.4,4.4,3.7,0.8,0.3,1.9,1.3,7.8,False
3,2018,"EuroLeague, Liga ACB",37.0,NaN,24.6,4.9,10.5,0.473,1.6,4.9,...,1.1,4.5,5.6,4.6,1.1,0.3,2.1,1.3,15.8,False

In [6]:
df = p.stats_per_game(kind='P', level='B')

print(len(df))

3

In [7]:
df.head()

,season,lg_name,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,fg3a_per_g,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2015,Liga ACB,2.0,NaN,8.0,0.5,1.5,0.333,0.0,0.5,...,0.0,2.0,2.0,0.0,0.0,0.0,0.5,0.0,1.0,True
1,2016,Liga ACB,8.0,NaN,8.0,1.3,2.4,0.526,0.3,1.1,...,0.3,1.4,1.6,0.9,0.3,0.1,0.9,1.6,3.1,True
2,2017,Liga ACB,10.0,NaN,19.2,2.3,6.0,0.383,0.5,2.4,...,0.9,3.8,4.7,2.7,0.3,0.0,1.3,1.1,6.5,True

In [8]:
df = p.stats_per_game(kind='B', level='B')

print(len(df))

7

In [9]:
df.head()

,season,lg_name,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,fg3a_per_g,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2015,Liga ACB,3.0,NaN,2.7,0.3,1.0,0.333,0.3,0.7,...,0.3,0.3,0.7,0.0,0.0,0.0,0.0,0.3,2.0,False
1,2016,"Liga ACB, EuroLeague",43.0,NaN,13.3,1.4,2.9,0.500,0.5,1.3,...,0.5,2.2,2.7,2.0,0.3,0.3,1.4,1.5,4.5,False
2,2017,"Liga ACB, EuroLeague",67.0,NaN,19.9,2.6,5.7,0.446,1.0,2.9,...,1.0,3.4,4.4,3.7,0.8,0.3,1.9,1.3,7.8,False
3,2018,"EuroLeague, Liga ACB",37.0,NaN,24.6,4.9,10.5,0.473,1.6,4.9,...,1.1,4.5,5.6,4.6,1.1,0.3,2.1,1.3,15.8,False
4,2015,Liga ACB,2.0,NaN,8.0,0.5,1.5,0.333,0.0,0.5,...,0.0,2.0,2.0,0.0,0.0,0.0,0.5,0.0,1.0,True

## Test: level='C' - Club

In [10]:
df = p.stats_per_game(kind='R', level='C')

print(len(df))

4

In [11]:
df.head()

,season,team_name_season,lg_name,lg_country,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2015,/euro/teams/real-madrid/2015.html,Liga ACB,es,3.0,NaN,2.7,0.3,1.0,0.333,...,0.3,0.3,0.7,0.0,0.0,0.0,0.0,0.3,2.0,False
1,2016,/euro/teams/real-madrid/2016.html,Liga ACB,es,31.0,NaN,14.2,1.6,3.1,0.526,...,0.6,2.2,2.8,2.0,0.4,0.3,1.5,1.9,4.9,False
2,2017,/euro/teams/real-madrid/2017.html,Liga ACB,es,32.0,NaN,19.9,2.7,5.8,0.460,...,1.0,3.3,4.3,3.1,0.7,0.4,2.0,1.3,7.8,False
3,2018,/euro/teams/real-madrid/2018.html,Liga ACB,es,17.0,NaN,23.6,4.6,9.8,0.473,...,1.1,4.8,5.9,4.6,0.9,0.2,1.9,1.6,14.1,False

In [12]:
df = p.stats_per_game(kind='P', level='C')

print(len(df))

3

In [13]:
df.head()

,season,team_name_season,lg_name,lg_country,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2015,/euro/teams/real-madrid/2015.html,Liga ACB,es,2.0,NaN,8.0,0.5,1.5,0.333,...,0.0,2.0,2.0,0.0,0.0,0.0,0.5,0.0,1.0,True
1,2016,/euro/teams/real-madrid/2016.html,Liga ACB,es,8.0,NaN,8.0,1.3,2.4,0.526,...,0.3,1.4,1.6,0.9,0.3,0.1,0.9,1.6,3.1,True
2,2017,/euro/teams/real-madrid/2017.html,Liga ACB,es,10.0,NaN,19.2,2.3,6.0,0.383,...,0.9,3.8,4.7,2.7,0.3,0.0,1.3,1.1,6.5,True

In [14]:
df = p.stats_per_game(kind='B', level='C')

print(len(df))

7

In [15]:
df.head()

,season,team_name_season,lg_name,lg_country,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2015,/euro/teams/real-madrid/2015.html,Liga ACB,es,3.0,NaN,2.7,0.3,1.0,0.333,...,0.3,0.3,0.7,0.0,0.0,0.0,0.0,0.3,2.0,False
1,2016,/euro/teams/real-madrid/2016.html,Liga ACB,es,31.0,NaN,14.2,1.6,3.1,0.526,...,0.6,2.2,2.8,2.0,0.4,0.3,1.5,1.9,4.9,False
2,2017,/euro/teams/real-madrid/2017.html,Liga ACB,es,32.0,NaN,19.9,2.7,5.8,0.460,...,1.0,3.3,4.3,3.1,0.7,0.4,2.0,1.3,7.8,False
3,2018,/euro/teams/real-madrid/2018.html,Liga ACB,es,17.0,NaN,23.6,4.6,9.8,0.473,...,1.1,4.8,5.9,4.6,0.9,0.2,1.9,1.6,14.1,False
4,2015,/euro/teams/real-madrid/2015.html,Liga ACB,es,2.0,NaN,8.0,0.5,1.5,0.333,...,0.0,2.0,2.0,0.0,0.0,0.0,0.5,0.0,1.0,True

## Test: level='E' - Eurocup/Euroleague (because Eurocup/Euroleague will never have sep playoffs, kind modifier does nothing) -> need to deal with duplicate when kind='B'

In [16]:
df = p.stats_per_game(kind='B', level='E')

print(len(df))

6

In [17]:
df.head()

,season,team_name_season,lg_name,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2016,/euro/teams/real-madrid/2016.html,EuroLeague,12.0,NaN,11.1,0.9,2.3,0.407,0.4,...,0.3,2.1,2.3,2.0,0.2,0.3,1.2,0.6,3.5,False
1,2017,/euro/teams/real-madrid/2017.html,EuroLeague,35.0,NaN,19.9,2.4,5.6,0.434,1.1,...,0.9,3.5,4.5,4.2,0.9,0.2,1.8,1.3,7.8,False
2,2018,/euro/teams/real-madrid/2018.html,EuroLeague,20.0,NaN,25.5,5.2,11.0,0.473,1.9,...,1.1,4.4,5.4,4.6,1.2,0.4,2.2,1.1,17.3,False
3,2016,/euro/teams/real-madrid/2016.html,EuroLeague,12.0,NaN,11.1,0.9,2.3,0.407,0.4,...,0.3,2.1,2.3,2.0,0.2,0.3,1.2,0.6,3.5,True
4,2017,/euro/teams/real-madrid/2017.html,EuroLeague,35.0,NaN,19.9,2.4,5.6,0.434,1.1,...,0.9,3.5,4.5,4.2,0.9,0.2,1.8,1.3,7.8,True

In [18]:
df = p.stats_per_game(kind='R', level='E')

print(len(df))

3

In [19]:
df.head()

,season,team_name_season,lg_name,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2016,/euro/teams/real-madrid/2016.html,EuroLeague,12.0,NaN,11.1,0.9,2.3,0.407,0.4,...,0.3,2.1,2.3,2.0,0.2,0.3,1.2,0.6,3.5,False
1,2017,/euro/teams/real-madrid/2017.html,EuroLeague,35.0,NaN,19.9,2.4,5.6,0.434,1.1,...,0.9,3.5,4.5,4.2,0.9,0.2,1.8,1.3,7.8,False
2,2018,/euro/teams/real-madrid/2018.html,EuroLeague,20.0,NaN,25.5,5.2,11.0,0.473,1.9,...,1.1,4.4,5.4,4.6,1.2,0.4,2.2,1.1,17.3,False

In [20]:
df = p.stats_per_game(kind='P', level='E')

print(len(df))

3

In [21]:
df.head()

,season,team_name_season,lg_name,g,gs,mp_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,is_playoffs
0,2016,/euro/teams/real-madrid/2016.html,EuroLeague,12.0,NaN,11.1,0.9,2.3,0.407,0.4,...,0.3,2.1,2.3,2.0,0.2,0.3,1.2,0.6,3.5,True
1,2017,/euro/teams/real-madrid/2017.html,EuroLeague,35.0,NaN,19.9,2.4,5.6,0.434,1.1,...,0.9,3.5,4.5,4.2,0.9,0.2,1.8,1.3,7.8,True
2,2018,/euro/teams/real-madrid/2018.html,EuroLeague,20.0,NaN,25.5,5.2,11.0,0.473,1.9,...,1.1,4.4,5.4,4.6,1.2,0.4,2.2,1.1,17.3,True